name: Web Programming @ UMass
description: COMPSCI 326
# theme: jekyll-theme-slate
# theme: minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: false
logo: "/umass_netscape_05.png"
url: "http://web-programming.org"
